version: "3.5"
services:
  db:
    image: mysql:5.7
    container_name: mysql_testdesis
    #restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sistema_votacion
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: testdesis
      MYSQL_USER: hernan
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./:/docker-entrypoint-initdb.d
    networks:
      - testdesis
      - default
  backend-miganado:
    # build:
    #   args:
    #     user: hernan
    #     uid: 1000
    #   context: ./
    #   dockerfile: Dockerfile
    image: php:7.4-fpm
    container_name: php_testdesis
    #restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - testdesis
      - default
  nginx_php:
    image: nginx:1.17-alpine
    container_name: nginx_testdesis
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - testdesis
  php-nginx:
    image: trafex/php-nginx
    container_name: php_nginx_testdesis
    ports:
      - 8001:8080
    volumes:
      - ./:/var/www/html
      #- ./nginx:/etc/nginx/conf.d
    networks:
      - testdesis

networks:
  testdesis:
    name: testdesis
    driver: bridge