version: "3.5"
services:
  db:
    image: mysql:5.7
    container_name: mysql_testdesis
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sistema_votacion
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: testdesis
      MYSQL_USER: hernan
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - testdesis
      - default
  php-nginx:
    image: trafex/php-nginx
    container_name: php_nginx_testdesis
    ports:
      - 8001:8080
    volumes:
      - ./php:/var/www/html 
      - ./nginx/app.conf:/etc/nginx/conf.d/server.conf
      #- ./nginx:/etc/nginx/conf.d
    networks:
      - testdesis

networks:
  testdesis:
    name: testdesis
    driver: bridge